# Generated by Django 3.0.1 on 2020-01-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
