# Generated by Django 3.0.1 on 2020-01-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20200116_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='Customer_Id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='Customer_Id',
        ),
    ]
