# Generated by Django 3.0.1 on 2020-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(max_length=10)),
                ('Customer_Name', models.CharField(max_length=250)),
                ('Customer_Address', models.CharField(max_length=50)),
                ('Customer_Contact', models.CharField(max_length=10)),
                ('Customer_Password', models.CharField(max_length=50)),
                ('Customer_Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
